
CREATE TABLE Average (
    AverageID BIGINT NOT NULL AUTO_INCREMENT,
    Saison INT NOT NULL,
    LeagueID BIGINT NULL,
    Position INT NOT NULL,
    PlayerName VARCHAR(255) NOT NULL,
    PlayerID BIGINT NOT NULL,
    HomeGameCount INT DEFAULT 0,
    GuestGameCount INT DEFAULT 0,
    TotalGameCount INT DEFAULT 0,
    HomeAverage DOUBLE(5,1) DEFAULT 0.0,
    GuestAverage DOUBLE(5,1) DEFAULT 0.0,
    TotalAverage DOUBLE(5,1) DEFAULT 0.0,
    HomePoints DOUBLE(3,1) DEFAULT 0.0,
    GuestPoints DOUBLE(3,1) DEFAULT 0.0,
    TotalPoints DOUBLE(3,1) DEFAULT 0.0,
    MissAverage DOUBLE(3,1) DEFAULT 0.0,
    Lowest INT NULL,
    Highest INT NULL,
    PRIMARY KEY (AverageID),
    FOREIGN KEY (PlayerID) REFERENCES Player(PlayerID) ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (LeagueID) REFERENCES League(LeagueID) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB;