CREATE TABLE ClubCalendar (
    EventID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    EventDate DATE NOT NULL,
    GameID BIGINT NULL,
    TeamID BIGINT NULL,
    FOREIGN KEY (GameID) REFERENCES Game(GameID),
    FOREIGN KEY (TeamID) REFERENCES Team(TeamID)
) ENGINE=InnoDB;