CREATE TABLE GameDays (
    SWID BIGINT NOT NULL,
    Saison INT NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Week INT NULL,
    Day DATE NULL,
    Number INT NULL,
    LeagueID BIGINT NOT NULL,
    FOREIGN KEY (LeagueID) REFERENCES League(LeagueID),
    PRIMARY KEY (SWID, Saison)
) ENGINE=InnoDB;