CREATE TABLE GameDetails (
    GameID BIGINT NOT NULL,
    TeamID BIGINT NOT NULL,
    PlayerID BIGINT NOT NULL,
    Position INT NOT NULL,
    LaneFirst INT DEFAULT 0,
    LaneSecond INT DEFAULT 0,
    LaneThird INT DEFAULT 0,
    LaneForth INT DEFAULT 0,
    Total INT DEFAULT 0,
    PlayerPoints DOUBLE(3,1) DEFAULT 0.0,
    TeamPoint DOUBLE(3,1) DEFAULT 0.0,
    Exchanged BOOLEAN DEFAULT false,
    ExchangedAt INT DEFAULT 0,
    PRIMARY KEY (GameID, TeamID, PlayerID),
    FOREIGN KEY (GameID) REFERENCES Game (GameID) ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (TeamID) REFERENCES Team (TeamID) ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (PlayerID) REFERENCES Player (PlayerID) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE GameAnalyse (
    GameAnalyseID BIGINT NOT NULL AUTO_INCREMENT,
    Saison INT NOT NULL,
    GameID BIGINT NOT NULL,
    PlayerID BIGINT NOT NULL,
    LaneOneFull INT NULL,
    LaneOneClear INT NULL,
    LaneOneMiss INT NULL,
    LaneTwoFull INT NULL,
    LaneTwoClear INT NULL,
    LaneTwoMiss INT NULL,
    LaneThreeFull INT NULL,
    LaneThreeClear INT NULL,
    LaneThreeMiss INT NULL,
    LaneFourFull INT NULL,
    LaneFourClear INT NULL,
    LaneFourMiss INT NULL,
    TotalFull INT NULL,
    TotalClear INT NULL,
    TotalMiss INT NULL,
    PRIMARY KEY (GameAnalyseID, Saison, GameID),
    FOREIGN KEY (PlayerID) REFERENCES Player(PlayerID),
    FOREIGN KEY (GameID) REFERENCES Game(GameID)
) ENGINE=InnoDB;
