
CREATE TABLE Game (
    GameID BIGINT NOT NULL AUTO_INCREMENT,
    Saison INT NOT NULL,
    HomeTeam BIGINT NOT NULL,
    HomePlayerPoints DOUBLE(3,1) NULL DEFAULT 0.0,
    HomeTeamPoints DOUBLE(3,1) NULL DEFAULT 0.0,
    HomeTotal INT NULL DEFAULT 0,
    GuestTeam BIGINT NOT NULL,
    GuestPlayerPoints DOUBLE(3,1) NULL DEFAULT 0.0,
    GuestTeamPoints DOUBLE(3,1) NULL DEFAULT 0.0,
    GuestTotal INT NULL DEFAULT 0,
    GameDay DATETIME NOT NULL,
    LeagueID BIGINT NOT NULL,
    SWID VARCHAR(20) NULL,
    PRIMARY KEY (GameID),
    FOREIGN KEY (HomeTeam) REFERENCES Team (TeamID) ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (GuestTeam) REFERENCES Team (TeamID) ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (LeagueID) REFERENCES League (LeagueID) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB;
