CREATE TABLE ScoreBoard (
    ScoreBoardID BIGINT NOT NULL AUTO_INCREMENT,
    Saison INT NOT NULL,
    LeagueID BIGINT NOT NULL,
    Position INT NOT NULL,
    TeamID INT NOT NULL,
    TeamName VARCHAR(255) NOT NULL,
    District VARCHAR(20) NULL,
    TotalGameCount INT NOT NULL,
    TotalTP INT NOT NULL,
    TotalMP DOUBLE(3,1) NOT NULL,
    HomeGameCount INT NOT NULL,
    HomeTP INT NOT NULL,
    HomeMP DOUBLE(3,1) NOT NULL,
    GuestGameCount INT NOT NULL,
    GuestTP INT NOT NULL,
    GuestMP DOUBLE(3,1) NOT NULL,
    SWID VARCHAR(20) NULL,
    PRIMARY KEY (ScoreBoardID),
    FOREIGN KEY (LeagueID) REFERENCES League (LeagueID) ON UPDATE RESTRICT ON DELETE RESTRICT
    FOREIGN KEY (TeamID) REFERENCES Team (TeamID) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB;